pdf:
	-pdflatex Answer_1
	-bibtex Answer_1
	-pdflatex Answer_1
	-pdflatex Answer_1
	
clean:
	-rm ep-annihilation.600pk
	-rm ep-annihilation.mf
	-rm ep-annihilation.tfm
	-rm Answer_1.aux
	-rm Answer_1.bbl
	-rm Answer_1.blg
	-rm Answer_1.log
	-rm Answer_1.pdf
	-rm Answer_1.dvi
